const MenuCompany = [
  {
    path: "/dashboard",
    icon: "fa fa-th",
    title: "Dashboard",
    children: [{ path: "/dashboard/v2", title: "Dashboard Martial Arts" }],
  },
  {
    path: "/Calendar & Planning",
    icon: "fa fa-calendar text-yellow",
    title: "Calendar & Planning",
    badge: "10",
    children: [
      { path: "/calendar", icon: "fa fa-calendar", title: "Calendar" },
      { path: "/calendar/events",title: "Events" },
      { path: "/scheduler", title: "Scheduler" },
    ],
  },

  {
    path: "/Users",
    icon: "fa fa-address-book text-orange",
    title: "Users",
    children: [
      { path: "/user/userroles", title: "Admin User-Roles" },
      { path: "/user/userroles/new", title: "Add User-Role" },
      { path: "/user/modulepermissions", title: "Admin Module-Permissions" },
      { path: "/user/modulepermissions/new", title: "Add Module-Permission" },
      { path: "/user/rightspermissions", title: "Rights & Permissions" },
      { path: "/user/rightspermissions/new", title: "Add new Rights & Permissions",},
      { path: "/user/users", title: "Users" },
      { path: "/user/users/new", title: "Add User" },
      { path: "/user/accountants", title: "Accountants" },
      { path: "/user/accountants/new", title: "Add Accountant" },
      { path: "/user/receptions", title: "Receptions" },
      { path: "/user/receptions/new", title: "Add Reception" },
      { path: "/user/supervisors", title: "Supervisors" },
      { path: "/user/search_user", title: "Search in Users" },
      { path: "/user/contacts", title: "Contacts" },
    ],
  }
  ,
 {
		path: "/Users",
		icon: "fa fa-lock text-orange",
		title: "Role & Permissions",
		badge: "10",
		children: [
			{ path: "/user/userroles", title: "Admin User-Roles" },			
			{ path: "/user/modulepermissions", title: "Admin Module-Permissions" },
			{ path: "/user/modulepermissions/new", title: "Add Module-Permission" },	
		],
  },
  
  {
    path: "/Human Resources",
    icon: "fa fa-graduation-cap text-red",
    title: "Human Resources",
    children: [
      { path: "/user/skills", title: "Skills" },
      { path: "/user/shifts", title: "Shifts" },
      { path: "/user/leaves", title: "Leaves" },
      { path: "/user/certificates", title: "Certificates" },
      { path: "/user/attendances", title: "Attendances" },
      { path: "/planning/adminskills", title: "Admin Skills" },
      { path: "/planning/admincertificates", title: "Admin Certificates" },
      { path: "/user/adminshifts", title: "Admin Shifts" },
      { path: "/planning/leavereasons", title: "Admin Leave-Reasons" },
      { path: "/planning/adminskills", title: "Admin Skills" },
    ],
  },

  {
    path: "/AIML",
    icon: "fa fa-gem text-lightblue",
    title: "AIML",
    children: [
      { path: "/AIML/AIMLsetting", title: "Setting" },
      { path: "/metai/yourdrive", title: "Import Data" },
      { path: "/AIML/AIserviceproviderlists", title: "AI Service Providers List"},
      { path: "/AIML/AIserviceproviders", title: "AI Service Providers" },
      { path: "/AIML/AIssistants/new", title: "Add AIssistants" },
      { path: "/AIML/AIssistants", title: "AIssistants" },
      { path: "/AIML/AIMLtasks", title: "AIML Tasks" },
      { path: "/AIML/AIMLtasksHarsha", title: "AIML Tasks Harsha" },		    
      { path: "AIML/LabelStudio", title: "Label Studio" },      ,
    ],
  },
    {
        path: "/Chatbots",
        icon: "fas fa-comments text-indigo",
        title: "Chatbots",
        children: [
            { path: "/chatbot/consult", title: "Consults" },
            { path: "/chatbot/setting", title: "Setting" },
            { path: "/chatbot/imexports", title: "Import Export Manager" },
            { path: "/chatbot/conversations", title: "Conversations" },
            { path: "/chatbot/companies", title: "Companies" },
            { path: "/chatbot/APIs", title: "Manage APIs" },
            { path: "/labelstudio", title: "Label Studio" },
            { path: "/chatbot/drive", title: "Your Drive",
                children: [
                    { path: "/menu/menu-1-1/menu-2-2", title: "Menu 2.2" },
                ],
            },
        ],
    },
  
   {
    path: "/martial", icon: "fa fa-futbol text-lightbrown", title: "Martial Arts",
    children: [
      { path: "/martial/industries", title: "Industries" },
      { path: "/martial/belts", title: "Belts" },
      // { path: "/martial/belts/new", title: "Add Belt" },      
      { path: "/martial/tournements", title: "Tournements" },
      { path: "/martial/trainings", title: "Trainings" },
      { path: "/martial/schools", title: "Schools" },
      { path: "/martial/schools/new", title: "Add School/Club" },      
      { path: "/martial/federations/", title: "Federations" },
      { path: "/martial/federations/new", title: "Add Federation" },      
      { path: "/martial/athletes/", title: "Athletes" },
      { path: "/martial/athletes/new", title: "Add Athlete" },      
      { path: "/martial/coachs", title: "Coachs" },
      { path: "/martial/coachs/new", title: "Add Coach" },      
      { path: "/martial/examinators/", title: "Examinators" },
      { path: "/martial/examinators/new", title: "Add Examinator" },      
      { path: "/martial/referees/", title: "Referees" },
      { path: "/martial/referees/new", title: "Add Referee" },      
    ],
  },
   {
    path: "/Accounting",
    icon: "fas fa-balance-scale text-cyan",
    title: "Accounting",
    badge: "10",
    children: [
      { path: "/accounting/accountingsetting", title: "Setting" },	
      { path: "/accounting/invoices", title: "Invoices" },
      { path: "/accounting/invoices/new", title: "Add Invoice" },
      { path: "/accounting/expenses", title: "Expenses" },
      { path: "/accounting/expenses/new", title: "Add Expense" },
      { path: "/accounting/transactions", title: "Transactions" },
      { path: "/accounting/transactions/new", title: "Add transaction" },
      { path: "/accounting/COAs", title: "COAs" },
      { path: "/accounting/COAs/new", title: "Add COA" },
      { path: "/accounting/services", title: "Services" },
      { path: "/accounting/services/new", title: "Add Service" },
      { path: "/accounting/products", title: "Products" },
      { path: "/accounting/products/new", title: "Add Product" },
      { path: "/accounting/profitlossstatement", title: "Profit vs Loss Statement"},
      { path: "/accounting/charts", title: "Charts" },
    ],
  },	
];

export default MenuCompany;
